version: "3.8"

services:
  database:
    container_name: "go-bank"
    image: "postgres:latest"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank
    ports:
      - '5444:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: