version: "3.8"

services:
  database:
    container_name: "go-bank-pg"
    image: "postgres:12.8"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank
    ports:
      - '5444:5432'
    volumes:
      - db:/var/lib/postgresql/data

networks:
  default:
    name: gobank
    external: true

volumes:
  db: