version: 3.8

services:
  api:
    image: dekuyo/gobank-api:0.1
    secrets:
      - gobank_database_url
      - gobank_symmetric_key
      - gobank_database_migration_path
      - gobank_database_driver
    environment:
      - DATABASE_URL_FILE=/run/secrets/gobank_database_url
      - SYMMETRIC_KEY_FILE=/run/secrets/gobank_symmetric_key
      - MIGRATION_DIRECTORY=file:///migration
      - DATABASE_DRIVER=postgres
    ports:
      - "9001:8000"
    extra_hosts:
          - "host.docker.internal:host-gateway"

  gapi:
    image: dekuyo/gobank-gapi:0.1
    secrets:
      - gobank_database_url
      - gobank_symmetric_key
      - gobank_database_migration_path
      - gobank_database_driver
    environment:
      - DATABASE_URL_FILE=/run/secrets/gobank_database_url
      - SYMMETRIC_KEY_FILE=/run/secrets/gobank_symmetric_key
      - MIGRATION_DIRECTORY=file:///migration
      - DATABASE_DRIVER=postgres
    ports:
      - "9002:8000"
    extra_hosts:
          - "host.docker.internal:host-gateway"

  gateway:
    image: dekuyo/gobank-gateway:0.1
    secrets:
      - gobank_database_url
      - gobank_symmetric_key
      - gobank_database_migration_path
      - gobank_database_driver
    environment:
      - DATABASE_URL_FILE=/run/secrets/gobank_database_url
      - SYMMETRIC_KEY_FILE=/run/secrets/gobank_symmetric_key
      - MIGRATION_DIRECTORY=file:///migration
      - DATABASE_DRIVER=postgres
    ports:
      - "9003:8000"
    extra_hosts:
          - "host.docker.internal:host-gateway"

secrets:
  gobank_database_url:
    external: true
  gobank_symmetric_key:
    external: true