# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  services:
    postgres:
      image: postgres:latest
      env:
        POSTGRES_PASSWORD: ${ POSTGRES_TEST_PASSWORD }
        POSTGRES_USER: ${ POSTGRES_TEST_USER }
        POSTGRES_DB: ${ POSTGRES_TEST_DB }
      ports:
        - 5444:5432
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install go-migration
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.darwin-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/
        which migrate

    - name: Run migrations
      run: make migrateUp

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
